[package]
name = "nom_duration_parser"
version = "0.1.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]

[dependencies]
duration = { path = "../duration"}
nom = "4"
random_durations = { path= "../random_durations" }
proptest = "0.8"